### ISSUE TITLE
Operator not cleaning up old aide.log.backup and aide.db.gz.backup files

### ISSUE THREAD

**Issue by ribua** [openshift/file-integrity-operator#201]
Presently we are running the file integrity operator , however it is filling up the /etc/kubernetes directory with files dating back from more than 3-4 months. Is there a way for us to clean up the files automatically after 30 or a certain  period so that it doesn't use up the space and fill up the disk drive.  The clean up using logrotate would also be a feasible option since it is already available in coreos. 

`sh-4.4# ls -al aide.db.gz.backup* |wc -l
252`

`sh-4.4# ls -al aide.log.backup* |wc -l
252`

**Comment by mrogers950** [comment]
Thanks for the report, we definitely should have the operator clean up old entries.

**Comment by alexisph** [comment]
We're using v0.1.16 and we have this issue as well.

**Comment by mrogers950** [comment]
v0.1.23 has the `maxBackups` pruning option now.
