### ISSUE TITLE
feature request: add `s390x` / multi arch support

### ISSUE THREAD

**Issue by skuethe** [openshift/file-integrity-operator#216]
I would like to request support for `s390x` architecture.
Or maybe you have a roadmap for releasing the official operators for the supported archs like `s390x` and `ppc64le` already and can share that?

I just saw that the `compliance-operator` f.e. has some multi arch PRs merged recently, so maybe there is something in the works here as well? 
- https://github.com/openshift/compliance-operator/pull/768
- https://github.com/openshift/compliance-operator/pull/795

Looking forward for some feedback :) Thank you!

**Comment by mrogers950** [comment]
s390x and ppc64le builds will be available for v0.1.28 from the RH Catalog.
