### ISSUE TITLE
Add initialDelay option

### ISSUE THREAD

**Issue by Vincent056** [openshift/file-integrity-operator#302]
When a user deploys FIO shortly after creating a new cluster, it activates quickly after the cluster is built. This can lead to problems when there are still updates being rolled out to the cluster and MCP getting updates. The file changes trigger failed FIO checks, resulting in unwanted alerts for every new cluster. To address this, we will discuss implementing an initialDelay option in FIO.

**Comment by rhmdnd** [comment]
Thanks for opening this, @Vincent056.

As an alternative to setting an initial delay timer, is there an attribute of the cluster that FIO can use to reason about the state of the install?

Will the `initialDelay` attribute need to be set on each scan/file integrity object?

If we had some API we could call to check the status of the install, we might be able to get away from introducing a new attribute altogether. FIO would wait to deploy any scans until after the cluster is ready by default.

**Comment by Vincent056** [comment]
Yes `initialDelay` would need to be set in each file integrity object, it will default to 0. I think everyone might have a different idea of the cluster being ready.

**Comment by Vincent056** [comment]
> Yes `initialDelay` would need to be set in each file integrity object, it will default to 0. I think everyone might have a different idea of the cluster being ready.

Yes initialDelay would need to be set in each file integrity object, it will default to 0. I think everyone might have a different idea of the cluster being ready.

**Comment by Vincent056** [comment]
@rhmdnd I have purposed the PR here: https://github.com/openshift/file-integrity-operator/pull/303

**Comment by rhmdnd** [comment]
Closing this since it was implemented and delivered in v1.2.0

https://github.com/openshift/file-integrity-operator/releases/tag/v1.2.0
