### ISSUE TITLE
e2e test node cleanup does not run

### ISSUE THREAD

**Issue by mrogers950** [openshift/file-integrity-operator#31]
Our e2e tests show these events:
`            "message": "Error creating: pods \"aide-clean-\" is forbidden: error looking up service account openshift-file-integrity/file-integrity-operator: serviceaccount \"file-integrity-operator\" not found",`
The service account is being cleaned up before the aide-clean deployment is created.

**Comment by JAORMX** [comment]
Why not make the test wait until the aide-clean is done? Then it could safely clean without order problems
