### ISSUE TITLE
Aide database stored on filesystem

### ISSUE THREAD

**Issue by jasinner** [openshift/file-integrity-operator#87]
I question the usefulness of this tool when the database is stored on the file system which is being checked. An motivated attacker could cover their tracks by altering the database directly. It should be stored in a place not writable by an attacker such as off-cluster or encrypted with keys that are stored off disk, such as on a Trusted Platform Module (TPM).

I think other file integrity checkers can use a TPM, such as [linux-ima](https://sourceforge.net/p/linux-ima/wiki/Home/), which should be used for secure boot in Centos/RHEL 9. That project is also under more recent development than aide. We seem to be including a version from Centos/RHEL 7 where which is 10 years old. Although the project has been updated as recently as last year.

**Comment by wmealing** [comment]
To satisfy the off-disk option for non TPM hardware (and also for remote attestation), the keylime project https://keylime.dev/ could be used.

**Comment by JAORMX** [comment]
I agree that using something such as keylime (that leverages IMA) would be better as a long-term solution. We intend to initially just cover the requirement of doing file integrity checks and rely on SELinux for protection. However, in the long run, we hope to enhance this operator for better coverage. Keylime indeed is in our radar.
